# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mdpoleto.github.io/
title: Marcelo D. Polêto
email: marcelodepolo@gmail.com
author: Marcelo D. Polêto
description: "Research scientist at USP-EEL."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: envelope-o
    title: email
    url: mailto:marcelodepolo@gmail.com
  - icon: flask
    title: scholar
    url: https://scholar.google.com/citations?user=sDHrqK4AAAAJ&hl
  - icon: file-pdf-o
    title: CV
    url: https://mdpoleto.github.io/rsc/full_CV_MDP.pdf
  - icon: github
    title: github
    url: https://github.com/mdpoleto
  - icon: twitter
    title: twitter
    url: https://twitter.com/mdpoleto
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/marcelodpoleto/
    
