title: Polêto
author: Marcelo D. Polêto

social:
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/marcelodpoleto/
  - icon: flask
    title: scholar
    url: https://scholar.google.com/citations?user=sDHrqK4AAAAJ&hl
  - icon: github
    title: github
    url: https://github.com/mdpoleto
  - icon: twitter
    title: twitter
    url: https://twitter.com/mdpoleto
  - icon: file-pdf-o
    title: resume
    url: https://DrQ.ai/rsc/resume.pdf
  - icon: envelope-o
    title: email
    url: mailto:marcelodepolo@gmail.com
