# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mdpoleto.github.io/
title: Marcelo D. Polêto
email: marcelodepolo@gmail.com
author: Marcelo D. Polêto
description: "Research scientist at USP-EEL."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: envelope-o
    title: Email
    url: mailto:mdpoleto@usp.br
  - icon: flask
    title: Scholar
    url: https://scholar.google.com/citations?user=sDHrqK4AAAAJ&hl
  - icon: file-pdf-o
    title: CV
    url: https://mdpoleto.github.io/rsc/full_CV_MDP.pdf
  - icon: github
    title: GitHub
    url: https://github.com/mdpoleto
  - icon: bluesky
    title: BlueSky
    url: https://bsky.app/profile/mdpoleto.bsky.social
  - icon: linkedin
    title: Linkedin
    url: https://www.linkedin.com/in/marcelodpoleto/
    
